### ISSUE TITLE
Is there a way to specify an "EqualsFactory"

### ISSUE THREAD

**Issue by zeitos** [SQiShER/java-object-diff#103]
Hi, 
   I took a look at the library and really liked it, I'm thinking about using it but I need a couple of extensions (that I might write if they are not available right now) one of which is:

I need a way to specify an equals method for objects that do not override equals and hashCode, from the quick look I took at the code that's not possible but before writing it I wanted to check.

Thanks!

**Comment by NagyGa1** [comment]
So, this feature for me (and probably for most of the JPA users) is more important than the list diff, due to these points:
 * we use lists in our domain model as sets: the position does not matter much, we prefer these because of the easier API (specially with JSF-like frontends) plus if we have overwritten hashCode and equals to use the JPA generated IDs, then the non-persistent => persistent transition would mess those sets up
 * as the list are managed by JPA, cannot (easily) replace the content with wrappers or proxies
 * JPA has some very specific requirement on hashCode and equals, can't change these for java-object-diff's sake
 * java-object-diff -ing is anyway context dependent, might want to define equals differently depending on the context

So the current java-object-diff list comparison, that treats them as sets, would be perfect for us if we can define a custom equals relationship.

I haven't started to look at the library's source code yet, but imagine one problem would be if it uses sets internally, these are hardwired to use hashCode and equals, no way to change that.

However, there might be a few options:
 * use TreeSet with a custom Comparator. With noting that TreeSet has different performance characteristics than HashSet. Might configure java-object-diff via its configuration API to use a specific comparator for a specific class, then if it is specified, TreeSet used, if not, the current default implementation.
 * don't use Sets, change the algo to facilitate custom equals.

**Comment by SQiShER** [comment]
@NagyGa1 Here are some pointers to get you started:

- `de.danielbechler.diff.differ.CollectionDiffer`
    
    Builds the diff of two collections. I recommend creating a copy and name it along the lines of "CollectionAsSetDiffer". That way we can make it configurable. We can come up with a better name later. :wink: 
- `de.danielbechler.util.Collections`

    Is used by the CollectionDiffer to extract sub-sets (added, removed & known items) of the given collections. It creates some new Lists, but I'm not sure if they are relevant for this feature. If they are, I'd just inline their usages into the new differ.

- `de.danielbechler.diff.access.Instances`

    Okay, so this thing is nasty. Mainly used as a value holder it also contains some logic to determine the relationship of the working and base object. There is a lot of equality checking going on here, that currently strictly uses the equals-method. I would not like to add more dependencies to this class, and rather keep it simple. But I think it would be a good idea to move the existing logic out of it and make it nothing more than a stupid data holder (maybe except for the access-method). That way, the logic becomes exchangeable.

I think that could actually work. But I'm still concerned about the merging-part. Since we don't have control over the target collection (for all we know it could be a super-weird home grown implementation),  we can't control how the collection determines object identity. So merging could result in unexpected results. Then again, maybe I'm overthinking it and should assume that people know the characteristics of their collections. But don't let this hold you back. I'm sure we'll figure this out, once the diffing part is solved.

**Comment by NagyGa1** [comment]
@SQiShER Ok, how about this:
 * New interface for configuration purposes:
   ```java
   public interface EqualsFactory {

        public boolean accepts(final Class<?> type);

        public boolean equals(final Object _this, final Object o);

        public int hashCode(final Object _this);

   }
   ```
 * CollectionDiffer#compare() currently works on `Collection<?>`. Would change those internally to `Collection<EqualsWrapper<?>>`, or maybe even `Set<EqualsWrapper<?>>`.
 * EqualsWrapper would just wrap the object and call its equals / hashCode(), or call a client supplied EqualsFactory:
    ```java
/**
 * Wraps an object and allows to specify custom equals by an EqualsFactory.
 */
public class EqualsWrapper {

	private Object o;

	private EqualsFactory equalsFactory;

	/**
	 * 
	 * @param o
	 *            the object to wrap
	 * @param equalsFactory
	 *            may be null, this case the object's own hashCode() and
	 *            equals() will be used.
	 */
	public EqualsWrapper(final Object o, final EqualsFactory equalsFactory) {
		this.o = o;
		this.equalsFactory = equalsFactory;
	}

	public Object getO() {
		return o;
	}

	@Override
	public int hashCode() {
		if(equalsFactory == null) {
			return o.hashCode();
		} else {
			return equalsFactory.hashCode(o);
		}
	}
	@Override
	public boolean equals(final Object obj) {
		if(equalsFactory == null) {
			return o.equals(obj);
		} else {
			return equalsFactory.equals(o, obj);
		}
	}
}
    ```

Maybe could make `EqualsWrapper` part of `Instances`? Then probably no need to change `CollectionDiffer` or `Collections`.

**Comment by SQiShER** [comment]
Yes, that could work. I'd try to avoid using the `EqualsWrapper` anywhere else than in the new `Differ` and its `Accessor` and `ElementSelector`. It should be completely transparent to the rest of the library. Otherwise you might end up retrieving an item and accidentally diffing against the wrapper instead of the original instance.

Here is me thinking out loud: 
- How would you implement the corresponding `Accessor` and `ElementSelector`? Would you store the wrapped instance as reference item?
- How would you find the equal counterpart in the target collection? Would you just walk through all target items and pass them to the equals method of the reference item to see if they are equal? 
- Does is make sense to provide an alternate `hashCode` method? The only place it's used is inside of the collections in order to optimize lookups. So the alternative `hashCode` would only be useful if we would replace all items in the target collection with wrapped versions. But that doesn't seem necessary. So I would just delegate the `hashCode` of the equals wrapper to the one of the underlying object.

Those are just some questions that come to mind. How would you go about them?

And one little nitpick: I would call it `EqualsStrategy` instead of `EqualsFactory`, since it doesn't really create any new instances and serves merely as a piece of exchangeable logic. This naming would also be more consistent with the rest of the configuration API (e.g. `ComparisonStrategy`).

**Comment by SQiShER** [comment]
@NagyGa1 /cc

**Comment by NagyGa1** [comment]
Ok, changed to `EqualsStrategy`.

I would keep the `hashCode` and use HashSets internally for the comparison, with an initial size of 1.5x of the array under comparison. This would perform well on large arrays as well (which is probably a rare case).

The next question is configuration: should there be a `EqualsConfigurer` that is parallel to the `ComparisonConfigurer`, and works largely the same way, or should `EqualsStrategy` be configured via `ComparisonConfigurer` somehow?

**Comment by NagyGa1** [comment]
Probably would just add on
```java
public interface ComparisonConfigurer
{
	Of ofNode(NodePath nodePath);

	Of ofType(Class<?> type);

	OfPrimitiveTypes ofPrimitiveTypes();

	ObjectDifferBuilder and();

	public interface Of
	{
		ComparisonConfigurer toUse(ComparisonStrategy comparisonStrategy);

		ComparisonConfigurer toEqualsStrategy(EqualsStrategy equalsStrategy);
...
```

**Comment by NagyGa1** [comment]
Please ignore it for a while, I am going to commit something soon and worth to have a look only after that.

**Comment by SQiShER** [comment]
:+1:

**Comment by celiovasconcelos** [comment]
I need this! :)
When using JPA @Entity sometimes you can't override equals and hashcode.

**Comment by SQiShER** [comment]
@celiovasconcelos I just release version 0.93. It contains this feature. The tests in [this package](https://github.com/SQiShER/java-object-diff/blob/master/src/integration-test/java/de/danielbechler/diff/identity/) show you how to use it. Please give it a try and let me know, if it works for you.
