### ISSUE TITLE
How to use Configuration? 

### ISSUE THREAD

**Issue by enigma969** [SQiShER/java-object-diff#132]
How can I use custom configuration for my DiffBuilder? I have seen that there are many different options available (https://github.com/SQiShER/java-object-diff/blob/master/docs/user-guide.md), but where are some JavaDocs or how do I use it? Is there a quick example of how to ignore collections (as fields in normal objects) in general? 

Thanks

**Comment by SQiShER** [comment]
Hi, sorry for the late response. The JavaDocs for every release get uploaded to [Maven Central](http://search.maven.org/#browse%7C1583566876). They are currently not hosted in a browsable fashion; mostly because nobody ever asked for it. But also because I don't see a huge benefit in it.

That being said, I designed the `ObjectDifferBuilder` to basically document itself via code completion.

You start building your `ObjectDiffer` like so:

```java
ObjectDifferBuilder.startBuilding().
```

And then code completion starts guiding you through the options. On the top level you'll find broad categories like `comparison()`, `inclusion()`, `filtering()`, etc. Each of these methods returns a subset of configuration options and a way to return back to the top-level. This is all designed with code completion in mind. So if you are using an IDE like Eclipse or IntelliJ you should be easily able to explore all the options. Most IDEs will also automatically fetch the JavaDocs and sources and show them to you whenever you need them.

Hope this helps. Feel free to reopen this ticket, in case you have any further questions.
