### ISSUE TITLE
Custom Node PropertyPath (ie: "toString") for PrintingVisitor

### ISSUE THREAD

**Issue by dacloutier** [SQiShER/java-object-diff#84]
Hi,
I'm trying to customize the propertyPath of a Node so that nested object use their "ID" fields instead of their memory adress.

Example:
Right now, the PrintingVisitor outputs:
Property at path '/myCollection[myCie.MyObj@6bfce612]/myProperty' has been added => [ 0 ]

But I would like to see:
Property at path '/myCollection[myCie.MyObj@123456]/myProperty' has been added => [ 0 ]

Where "123456" is the value of a field that I choose (the id property in my case)

How could I go about that?

Thanks,

David.

**Comment by airduster** [comment]
Follow up question regarding this. I am trying to achieve the same thing (renaming property path) but I do not wish to use the toString() solution.

 Do you have an example of a custom visitor implementation **renaming** a PropertyPath of an object inside a collection? 

From looking at the code understanding is the visitor is simply traversing all the nodes **after** the diff operation was executed (e.g after the toString()  method was invoked on the object inside the collection ).

**Comment by SQiShER** [comment]
@airduster I think the code of the [PrintingVisitor](https://github.com/SQiShER/java-object-diff/blob/master/src/main/java/de/danielbechler/diff/node/PrintingVisitor.java) is the closest example to what you're trying to do. If that doesn't help, have a look at some of the [other visitors](https://github.com/SQiShER/java-object-diff/tree/master/src/main/java/de/danielbechler/diff/node).  In the end, all you need to do is to implement this simple interface:

```java
public interface Visitor
{
	void node(DiffNode node, Visit visit);
}
```

In your case you'll also want to pass the `base` and `working` version of the compared object to the constructor, so you can use them to build a nice representation of what's changed. What this representation looks like is entirely up to you. There will be nothing standing between you and your original objects.

**Comment by airduster** [comment]
@SQiShER Thanks for the explanation. I already implemented a custom visitor but that is what I don't understand. How do you correlate back to **the specific attributes **inside the original base and working objects from inside the `CustomVisitor#node(...) `method? In my case the attribute is a Collection of Pojos. 

So when I invoke (inside the `CustomVisitor#node(...) `)

` NodePath nodePath = node.getPath();` 

It has already been populated with the TestObjTwo#toString() method on the changed pojo. My root object has a

`private Set<TestObjTwo> myCollection;`

attribute. When I add an entry to this collection and execute it through the custom visitor the `TestObjTwo#toString() `method is already invoked inside the node.getPath().

Please see the screenshots at the bottom for further illustration. 

---------------------------------------------------------------------------------------------------------------------

**My Question:**
So how do I reference the collection attribute on my root object + specific the specific pojo in the collection... inside the  CustomVisitor#node(...) method?

---------------------------------------------------------------------------------------------------------------------

![image](https://cloud.githubusercontent.com/assets/2158763/13545318/653ac2ae-e24d-11e5-8cfe-4650841261c5.png)

![image](https://cloud.githubusercontent.com/assets/2158763/13545336/c7146976-e24d-11e5-87d5-40942e681c72.png)

![image](https://cloud.githubusercontent.com/assets/2158763/13545340/f6449392-e24d-11e5-971e-4655bac2dc1b.png)

**Comment by SQiShER** [comment]
@airduster Ah, I see what you mean. The `NodePath` is not meant to access the values. It's just a way to query for specific nodes. The actual values are accessed via `DiffNode#canonicalGet`. There is a small example for that in the [Getting Started Guide](https://github.com/SQiShER/java-object-diff/blob/master/docs/getting-started.md#reading-values).

**Comment by airduster** [comment]
@SQiShER I am not really interested in the values (with regards to my question) my goal is to RENAME the nodepath because I want to display the node path to my user... but I want the nodepath to have a more "U.I friendly" naming rather than showing class names, attribute names, or toString() method. Is there a way to intercept or change how a nodepath is generated in the ObjectDiffer#diff(...) method?

**Comment by SQiShER** [comment]
Ok, the example makes it a bit more clear. I think you should let go from the `NodePath` idea and focus more on the `DiffNode`, because the NodePath won't get you very far. The example looks like you actually DO care about the values (e.g. "Michael David", "Chicago", "New York"). Since the output you want to create spans several nodes, you need to use the `getParentNode()` method of the changed leaf nodes (those without children) to walk back through the tree and extract the values from the parent objects via `canonicalGet`. That's the only way to achieve what you want to do. The `NodePath` is neither designed, nor capable of handing this case.
